framework/MGDB/urls.py
from django.urls import path

from . import views
from .models import *

urlpatterns = [
  path('', views.HomepageView.as_view(), name='home'),
  path('search/', views.SearchpageView.as_view(), name='search'),
  path('search_result/', views.SearchResultView.as_view(), name='search_result'),
  path('app_detail/<str:name>/<str:category>', views.AppDetailView.as_view(), name='app_detail'),
  path('ranking/', views.RankView.as_view(), name='ranking'),
  path('category/', views.CategoryView.as_view(), name='category'),
]

framework/framework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MGDB.urls'))
]

framework/MGDB/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# from django.contrib.postgres.fields import ArrayField

# Create your models here.

class Category(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name


class Tag(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name


class App(models.Model):
  name = models.CharField(max_length=50)
  developer = models.CharField(max_length=50)
  category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
  # tags = ArrayField(models.ForeignKey(Tag))
  # rank = models.IntegerField(default=999)
  # rating = models.FloatField(default=0)
  # popularity = models.IntegerField(default=0)
  description = models.TextField()
  imgUrl = models.CharField(max_length=100, default="#")

  def __str__(self):
    return self.name


class Banner(models.Model):
  name = models.CharField(max_length=50)
  id = models.IntegerField(unique=True, validators=[MinValueValidator(0), MaxValueValidator(2)], primary_key=True)
  imgUrl = models.CharField(max_length=100, default="#")

  def __str__(self):
    return self.name


class EditorPick(models.Model):
  id = models.IntegerField(unique=True, validators=[MinValueValidator(0), MaxValueValidator(2)], primary_key=True)
  app = models.ForeignKey(App, on_delete=models.CASCADE, blank=True)
  imgUrl = models.CharField(max_length=100, default="#")

  def __str__(self):
    return self.app.name


class Collection(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name


class MatchTable(models.Model):
  name = models.ForeignKey(Collection, on_delete=models.CASCADE)
  app = models.ForeignKey(App, on_delete=models.CASCADE)
  rank = models.IntegerField(validators=[MinValueValidator(0)])

  def __str__(self):
    return self.name.name + " : " + self.app.name + " : " + str(self.rank)

class SamplePic(models.Model):
  name = models.CharField(max_length=50)
  owner = models.ForeignKey(App, on_delete=models.CASCADE)
  imgUrl = models.CharField(max_length=100, default='#')

  def __str__(self):
    return self.owner.name + " : " + self.name

framework/MGDB/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from .models import *


# Create your views here.

class HomepageView(ListView):
  template_name = 'home.html'
  context_object_name = 'app'

  def get_queryset(self):
    return App.objects.all()

  def get_context_data(self, *, object_list=None, **kwargs):
    context = super(HomepageView, self).get_context_data(**kwargs)
    context['banner_list'] = Banner.objects.all()
    context['collection'] = MatchTable.objects.all()
    context['editor_pick'] = EditorPick.objects.all()
    return context


class SearchpageView(ListView):
  template_name = 'search.html'
  model = Category
  context_object_name = 'categorires'

  def get_queryset(self):
    return Category.objects.all()


class SearchResultView(ListView):
  template_name = 'search_result.html'
  context_object_name = 'search_result'

  def get_queryset(self):  # new
    name = self.request.GET.get('search')
    category = self.request.GET.get('category')
    object_list = App.objects.filter(name__contains=name).filter(category__name__contains=category)

    return object_list


class AppDetailView(ListView):
  template_name = 'app_details.html'
  model = App

  def get_context_data(self, *, object_list=None, **kwargs):
    context = super(AppDetailView, self).get_context_data(**kwargs)
    context['detail'] = App.objects.filter(name__exact=self.kwargs['name'])
    context['related'] = App.objects.filter(category__name__contains=self.kwargs['category']) \
      .exclude(name__exact=self.kwargs['name'])
    return context


class RankView(ListView):
  template_name = 'rankings.html'
  model = MatchTable
  context_object_name = 'table'

  def get_queryset(self):
    return MatchTable.objects.filter(name__name__exact='Top Games')


class CategoryView(ListView):
  template_name = 'category.html'
  context_object_name = 'app'

  def get_queryset(self):
    return App.objects.all()

  def get_context_data(self, *, object_list=None, **kwargs):
    context = super(CategoryView, self).get_context_data(**kwargs)
    context['categories'] = Category.objects.all()
    return context

framework/templates/app_details.html
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <!-- top bar -->
	<div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>
      </div>
    </div>

	<!-- content -->

    {% for app in detail %}
    <!-- app title -->
    <div class="col-12 games-display-bg">
        <div class="games-display-bg">
            <div class="col-2">
                <div class="games-display" style="height: 250px;"></div>
            </div>
            <div class="col-2">
                <div class="games-display">
                    <img src="{{ app.imgUrl }}">
                </div>
            </div>
            <div class="col-6">
                <div class="games-display" style="height: 250px;">
                    <div class="apptitle">
                        <p>{{ app.name }}</p>
                    </div>
                    <div class="appsubtitle" style="color:rgb(238,238,238)">
                        <p>{{ app.developer }}</p>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <div class="games-display" style="height: 250px;"></div>
            </div>
        </div>
    </div>
    <!-- app details  -->
    <div class = "col-2"></div>

    <div class="col-5">
    <div class="games-display2">

        <div class="apptitle2">
            Description
        </div>
        <div class="appdetails">
            <pre>{{ app.description }}</pre>
        </div>
        <br>
        <div class="appsubtitle">
            <p>Categories: </p>
        </div>
        <div class="appminordetails">
            {{ app.category.name }}
        </div>
    </div>
    <br>
    <div class="image-wrapper">
			<div id="slider4" class="text-center">
        {% for image in app.samplepic_set.all %}
          <div class="image-slide">
            <img src="{{ image.imgUrl }}">
          </div>
        {% endfor %}
			</div>
		</div>
    <br>

</div>
    {% endfor %}

	<div class="col-3">
		<div class="apptitle" style="padding-left: 20px;color:rgb(238,238,238)">
			<p>Related apps</p>
		</div>
        {% for app in related %}
            <div class="col-4"><a href="{% url 'app_detail' name=app.name category=app.category.name %}">
                  <img src="{{ app.imgUrl }}" style="width: 90%; padding-left:20px;padding-top:10px;">
              </a>
            </div>
        {% endfor %}
	</div>
	
	<div class="col-12">
      <div class="external-link" style="padding-bottom: 40px;">
        <br><br>
        <header>External Links</header>
        <br><br>
          <wrapper>
              <a href="https://play.google.com/store?hl=en">Play Store</a>
              <a href="https://www.apkmirror.com/">APK Mirror</a>
              <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
              <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
              </wrapper>
          <wrapper>
            <a>&nbsp;</a>
            <a>Ⓒ 2019 MGDB</a>
              <a>&nbsp;</a>
          </wrapper>
      </div>
    </div>

</body>
<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    // Next/previous controls
    function plusSlides(n) {
      showSlides((slideIndex += n));
    }

    // Thumbnail image controls
    function currentSlide(n) {
      showSlides((slideIndex = n));
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {
        slideIndex = 1;
      }
      if (n < 1) {
        slideIndex = slides.length;
      }
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active";
    }
</script>

</html>

framework/templates/category.html
{% load static %}
{% load operation %}
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>

      </div>
    </div>

    {% for category in categories %}
        <!-- 1 category -->
        <div class="col-12">
            <div class="category-banner">
                <header>{{ category.name }}</header>
            </div>
        </div>

        <div class="col-2"></div>
        <div class="col-8">
            <div class="category-page">
                {% for app in category.app_set.all %}
                    {% if forloop.counter0|modulo:5 == 0 %}
                        <display>
                    {% endif %}
                        <game><a href="{% url 'app_detail' name=app.name category=category.name %}"><img
                                src="{{ app.imgUrl }}">
                        <br>
                        {{ app.name }}</a></game>
                    {% if forloop.counter0|modulo_plusone:5 and forloop.counter0 != 0 %}
                        </display>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col-2"></div>

        <!-- end category -->
    {% endfor %}

    <div class="col-12">
        <div class="external-link" style="padding-bottom: 40px;">
            <br><br>
            <header>External Links</header>
            <br><br>
            <wrapper>
                <a href="https://play.google.com/store?hl=en">Play Store</a>
                <a href="https://www.apkmirror.com/">APK Mirror</a>
                <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
                <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
            </wrapper>
            <wrapper>
                <a>&nbsp;</a>
                <a>Ⓒ 2019 MGDB</a>
                <a>&nbsp;</a>
            </wrapper>
        </div>
    </div>

</body>

framework/templates/home.html
{% load static %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>

      </div>
    </div>

    <!-- Slideshow container -->
    <div class="slideshow-container">
      <!-- Full-width images with number and caption text -->
      <div class="mySlides fade">
        <div class="numbertext">1 / 3</div>
        {% for banner in banner_list %}
          {% if banner.id == 0 %}
            <a href="{% url 'ranking' %}">
              <img
                src="{{ banner.imgUrl }}"
                style="width:100%"
              />
            </a>
          {% endif %}
        {% endfor %}
      </div>

      <div class="mySlides fade">
        <div class="numbertext">2 / 3</div>
        {% for banner in banner_list %}
          {% if banner.id == 1 %}
            <a href="{% url 'app_detail' name='Azur Lane' category='Action' %}">
                <img src="{{ banner.imgUrl }}"
                     style="width:100%"
                />
            </a>
          {% endif %}
        {% endfor %}
      </div>

      <div class="mySlides fade">
        <div class="numbertext">3 / 3</div>
        {% for banner in banner_list %}
          {% if banner.id == 2 %}
            <a href="{% url 'category' %}">
              <img
                src="{{ banner.imgUrl }}"
                style="width:100%"
              />
            </a>
          {% endif %}
        {% endfor %}
      </div>

      <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
      
    </div>
    <br />

    <!-- The dots/circles -->
    <div style="text-align:center">
      <span class="dot" onclick="currentSlide(1)"></span>
      <span class="dot" onclick="currentSlide(2)"></span>
      <span class="dot" onclick="currentSlide(3)"></span>
    </div>

    <div class="col-12">
      <div class="ranking-label">
        <header>Top Games<br>
          <subheader>The best mobile games of all time.</subheader>
        </header>

        <display>
            {% for object in collection %}
              {% if object.name.name == "Top Games" %}
                {% if object.rank == 0 %}
                    <a href="{% url 'app_detail' name=object.app.name category=object.app.category.name %}">
                        <game><img src="{{ object.app.imgUrl }}"></game>
                    </a>
                {% endif %}
                {% if object.rank == 1 %}
                    <a href="{% url 'app_detail' name=object.app.name category=object.app.category.name %}">
                        <game><img src="{{ object.app.imgUrl }}"></game>
                    </a>
                {% endif %}
                {% if object.rank == 2 %}
                  <a href="{% url 'app_detail' name=object.app.name category=object.app.category.name %}">
                      <game><img src="{{ object.app.imgUrl }}"></game>
                  </a>
                {% endif %}
                {% if object.rank == 3 %}
                  <a href="{% url 'app_detail' name=object.app.name category=object.app.category.name %}">
                        <game><img src="{{ object.app.imgUrl }}"></game>
                    </a>
                {% endif %}
              {% endif %}
            {% endfor %}
        </display>
        <display>
          <button><a href="{% url 'ranking' %}" style="text-decoration: none;color:white">More</a></button>
        </display>
      <br><br>
      </div>
    </div>

    <div class="col-12">
      <div class="editor-label">
        <header>Editor's Picks</header><br>
        {% for banner in editor_pick %}
          {% if banner.id == 0 %}
            <a href="{% url 'app_detail' name=banner.app.name category=banner.app.category.name %}">
              <display>
                <img src="{{ banner.imgUrl }}"/>
              </display>
            </a>
          {% endif %}
          {% if banner.id == 1 %}
            <a href="{% url 'app_detail' name=banner.app.name category=banner.app.category.name %}">
              <display>
                <img src="{{ banner.imgUrl }}" />
              </display>
            </a>
          {% endif %}
          {% if banner.id == 2 %}
            <a href="{% url 'app_detail' name=banner.app.name category=banner.app.category.name %}">
              <display>
                <img src="{{ banner.imgUrl }}" />
              </display>
            </a>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    
    
		
    <div class="col-12">
      <div class="external-link" style="padding-bottom: 40px;">
        <br><br>
        <header>External Links</header>
        <br><br>
          <wrapper>
              <a href="https://play.google.com/store?hl=en">Play Store</a>
              <a href="https://www.apkmirror.com/">APK Mirror</a>
              <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
              <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
              </wrapper>
          <wrapper>
            <a>&nbsp;</a>
            <a>Ⓒ 2019 MGDB</a>
              <a>&nbsp;</a>
          </wrapper>
      </div>
    </div>
  </body>

  <script>
    var slideIndex = 1;
    showSlides(slideIndex);

    // Next/previous controls
    function plusSlides(n) {
      showSlides((slideIndex += n));
    }

    // Thumbnail image controls
    function currentSlide(n) {
      showSlides((slideIndex = n));
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {
        slideIndex = 1;
      }
      if (n < 1) {
        slideIndex = slides.length;
      }
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active";
    }
  </script>
</html>

framework/templates/rankings.html
{% load static %}
{% load operation %}
<html>
    
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
<body>
    <!-- top bar -->
     <div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>

      </div>
    </div>


    <div class="col-12">
        <div class="ranking-page-title">
            <header>Top Games of All Time<br><Br>
            </header>
        </div>
    <div class="col-2"></div>
    <div class="col-8">
        <div class="ranking-page">
            {% for row in table %}
                {% if row.rank|modulo:5 == 0 %}
                    <display>
                {% endif %}
                <game>
                    <a href="{% url 'app_detail' name=row.app.name category=row.app.category.name %}">
                        <img src="{{ row.app.imgUrl }}"><br>
                        {{ row.app.name }}
                    </a>
                </game>
                {% if row.rank|modulo_plusone:5 and row.rank != 0 %}
                    </display>
                {% endif %}
            {% endfor %}
            
            <br><br>
            </div>
        </div>
    </div>
    <div class="col-2"></div>
    <br>

    <div class="col-12">
      <div class="external-link" style="padding-bottom: 40px;">
        <br><br>
        <header>External Links</header>
        <br><br>
          <wrapper>
              <a href="https://play.google.com/store?hl=en">Play Store</a>
              <a href="https://www.apkmirror.com/">APK Mirror</a>
              <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
              <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
              </wrapper>
          <wrapper>
            <a>&nbsp;</a>
            <a>Ⓒ 2019 MGDB</a>
              <a>&nbsp;</a>
          </wrapper>
      </div>
    </div>
</body>
</html>

framework/templates/search.html
{% load static %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
   <div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>

      </div>
    </div>

    <!-- Content -->
    <br>
    <form action="{% url 'search_result' %}">
      <div class="col-12">
        <div class="search-label">
          <header>Search</header>
        </div>
      </div>

      <div class="search-container">
        <input
          type="text"
          placeholder="Search for a game..."
          name="search"
          style="width: 100%;background-color:transparent;
        border:none;font-size:30px;color:white;"
        />
        <input type="submit" />
      </div>

      <div class="col-12" style="margin-top: 50px;">
        <div class="search-advance">
          <header>Categories:</header>
          <wrapper>
            <input type="radio" name="category" value="" checked> None
            {% for category in categorires %}
                <input type="radio" name="category" value="{{ category.name }}"> {{ category.name }}
            {% endfor %}
          </wrapper>
        </div>
      </div>
    </form>
      <div class="col-12">
          <div class="external-link" style="padding-bottom: 40px;">
            <br><br>
            <header>External Links</header>
            <br><br>
              <wrapper>
                  <a href="https://play.google.com/store?hl=en">Play Store</a>
                  <a href="https://www.apkmirror.com/">APK Mirror</a>
                  <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
                  <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
                  </wrapper>
              <wrapper>
                <a>&nbsp;</a>
                <a>Ⓒ 2019 MGDB</a>
                  <a>&nbsp;</a>
              </wrapper>
          </div>
        </div>
  </body>

</html>

framework/templates/search_result.html
{% load static %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <div class="navbar">
      <a href="{% url 'home' %}">
        <img class="logo" src="{% static "assets/img/MGDB_text_icon.png" %}" style="margin-bottom:-8px; margin-top:-10px">
      </a>
      <div style="align-items: center;">
        <a href="{% url 'search' %}">Search</a>
        <div class="dropdown">
          <button class="dropbtn">
            Catalogue
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="{% url 'ranking' %}">Ranking</a>
            <a href="{% url 'category' %}">Categories</a>
          </div>
        </div>

      </div>
    </div>

    <!-- Content -->
    <div class="search-result_banner">
      <header>Results</header>
    </div>

    <div class="search-result">
      <div class="col-9">
        {% for app in search_result %}
          <container>
            <app>
              <a href="{% url 'app_detail' name=app.name category=app.category.name %}">
                  <img src="{{ app.imgUrl }}">
              </a>
              <detail>
                <name>{{ app.name }}</name><br>
                  <category>{{ app.category.name }}</category>
                <pre>
                  {{ app.description }}
                </pre>
              </detail>
            </app>
          </container>
        {% endfor %}
      </div>

      <div class="col-2">
        <back>
            <a href="{% url 'search' %}">Back</a><br>
        </back>
      </div>
    </div>

    <br>
    <br>
    <br>

    <div class="col-12">
      <div class="external-link" style="padding-bottom: 40px;">
        <br><br>
        <header>External Links</header>
        <br><br>
          <wrapper>
              <a href="https://play.google.com/store?hl=en">Play Store</a>
              <a href="https://www.apkmirror.com/">APK Mirror</a>
              <a href="https://www.apple.com/ios/app-store/">Apple App Store</a>
              <a href="https://www.apple.com/th/apple-arcade/">Apple Arcade</a>
              </wrapper>
          <wrapper>
            <a>&nbsp;</a>
            <a>Ⓒ 2019 MGDB</a>
              <a>&nbsp;</a>
          </wrapper>
      </div>
    </div>
  </body>
</html>